# Generated by Django 6.0.1 on 2026-01-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
    ]
