# Generated by Django 6.0.1 on 2026-01-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
    ]
