# Generated by Django 6.0.1 on 2026-01-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='Новое мероприятие: {title}', help_text='Используйте {title}, {date}, {venue} для подстановки значений.', max_length=255, verbose_name='Шаблон темы письма')),
                ('message_template', models.TextField(default='Приглашаем вас на {title}!\nМесто: {venue}\nДата: {date}', help_text='Используйте {title}, {date}, {venue}, {description} для подстановки.', verbose_name='Шаблон текста письма')),
                ('recipients_list', models.TextField(blank=True, default='', help_text='Введите email адреса через запятую.', verbose_name='Список адресатов (вручную)')),
                ('send_to_all_users', models.BooleanField(default=True, verbose_name='Отправлять всем зарегистрированным пользователям')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
    ]
