# Generated by Django 6.0.1 on 2026-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_emailnotificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationconfig',
            name='message_template',
            field=models.TextField(default='Приглашаем вас на {title}!\nМесто: {venue}\nДата: {date}\nОписание: {description}', help_text='Используйте {title}, {date}, {venue}, {description} для подстановки.', verbose_name='Шаблон текста письма'),
        ),
    ]
