# Generated by Django 6.0.1 on 2026-01-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_emailnotificationconfig_message_template'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='weather',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='weather.weathersnapshot'),
        ),
    ]
