# Generated by Django 6.0.1 on 2026-01-23 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_weather'),
        ('venues', '0002_alter_venue_options'),
        ('weather', '0002_alter_weathersnapshot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='preview_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='events/previews/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ENDED', 'Ended'), ('DELETED', 'Deleted')], db_index=True, default='DRAFT', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='venues.venue', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='weather',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='weather.weathersnapshot', verbose_name='Погода'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/images/', verbose_name='Файл'),
        ),
    ]
