# Generated by Django 6.0.1 on 2026-01-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.FloatField(help_text='Температура в °C')),
                ('humidity_percent', models.FloatField(help_text='Влажность в %')),
                ('pressure_mmhg', models.FloatField(help_text='Давление в мм рт.ст.')),
                ('wind_direction', models.CharField(help_text='Направление ветра (N/NE/E/SE/S/SW/W/NW)', max_length=10)),
                ('wind_speed_ms', models.FloatField(help_text='Скорость ветра в м/с')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
