# Generated by Django 6.0.1 on 2026-01-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_options'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathersnapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Снимок погоды', 'verbose_name_plural': 'Архив погоды'},
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='humidity_percent',
            field=models.IntegerField(verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='pressure_mmhg',
            field=models.IntegerField(verbose_name='Давление (мм рт.ст.)'),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='temperature_celsius',
            field=models.FloatField(verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='venues.venue', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='wind_direction',
            field=models.CharField(max_length=10, verbose_name='Направление ветра'), # <-- ПРАВИЛЬНО
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='wind_speed_ms',
            field=models.FloatField(verbose_name='Скорость ветра (м/с)'),
        ),
    ]
