# Generated by Django 6.0.1 on 2026-01-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weathersnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersnapshot',
            name='wind_direction',
            field=models.CharField(max_length=10, verbose_name='Направление ветра'),
        ),
    ]
