# Generated by Django 6.0.1 on 2026-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weathersnapshot_wind_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersnapshot',
            name='wind_direction',
            field=models.CharField(help_text='Направление ветра (N/NE/E/SE/S/SW/W/NW)', max_length=10, verbose_name='Направление ветра'),
        ),
    ]
